# conda env create -f environment.yml
name: lume-gpt-dev
channels:
  - conda-forge
dependencies:
  - python>3.9
  - numpy
  - scipy>=1.0.0
  - matplotlib
  - h5py
  - distgen
  - openpmd-beamphysics>=0.14.0
  - easygdf
# Developer
  - pip
